blank_issues_enabled: true
contact_links:
  - name: Twitter
    url: https://twitter.com/opendata_sco
    about: test
  - name: Slack
    url: https://join.slack.com/t/opendatascotland/shared_invite/zt-yfcc64tg-xIF1cOxkWbKZqI8ZBPzkGg
    about: Please ask and answer questions here.